version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx_backend
    ports:
      - "80:8000"
    volumes:
      - .:/app
      - ./etc/nginx:/etc/nginx/conf.d
    depends_on:
      - web

  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: adminadmin
      MYSQL_DATABASE: django
    volumes:
      - ./db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8082:80
    volumes:
      - /sessions

  web:
    build: .
    container_name: backend_django
    volumes:
      - .:/app
    expose:
      - "8000"
    depends_on:
      - db
