version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: backend_django
    volumes:
      - .:/app
    expose:
      - "8000"

      
